on: [push]
jobs:
   mail-on-push:
     runs-on: ubuntu-latest
     steps:
     - name: Send email
       uses: dawidd6/action-send-mail@v3
       with:
         server_address: smtp.gmail.com
         server_port: 465
         username: ${{secrets.MAIL_USERNAME}}
         password: ${{secrets.MAIL_PASSWORD}}
         subject: ase
         body: ase
         to: ang.tulusa@gmail.com
         from: Github actions
